### ISSUE TITLE
JSONEditor styling error

### ISSUE THREAD

**Issue by jerickbixly** [nnseva/django-jsoneditor#18]
hi. 

i was trying out the json editor in the django admin. i configured it by doing a formfield_override in the modelAdmin like so

```
    formfield_overrides = {
        JSONField:{ 'widget':JSONEditor },
    }
```

and in the settings file, i added the following lines

```
JSON_EDITOR_JS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.5.11/jsoneditor.js'
JSON_EDITOR_CSS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.5.11/jsoneditor.css'
```

however, it ended up looking like this

![cropped-admin-jsonfield](https://cloud.githubusercontent.com/assets/2738535/21754617/b1064722-d63e-11e6-92b0-63ed817bb930.png)

I then tried changing my model by using this JSONField

```
jsoneditor.fields.django_jsonfield.JSONField
```

and removing the formfield_override but the resulting display was still the same in my django admin. Am I missing anything in the way I set this up? thanks

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40749107-jsoneditor-styling-error?utm_campaign=plugin&utm_content=tracker%2F26137122&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F26137122&utm_medium=issues&utm_source=github).

**Comment by nnseva** [comment]
Please, give me some details:
- version of the Django
- version of the python
- did you use `DEBUG=true` in `settings.py`?
- did you add `'jsoneditor'` into `INSTALLED_APPS` parameter in `settings.py`?
- did you use `python manage.py collectstatic` management command?

**Comment by jerickbixly** [comment]
hi @nnseva . django version is 1.7.8, python version is, 2.7.12, debug is true, jsoneditor was added into installed apps and collectstatic was run as well. 

thanks

**Comment by nnseva** [comment]
Unfortunately, I can not reproduce a problem locally, but found some mismatch that you can make.

The problem may be caused by the order of applications in `INSTALLED_APPS` settings. Please ensure that the `'jsoneditor'` application is present BEFORE `'django.contrib.staticfiles'` application (anyway, the `django.contrib.staticfiles` application should be present AFTER ALL other applications providing static files in your project).

Please ensure that all required static files are got without errors by your browser. For example, in order to do it using Chrome browser just press `<Ctrl>-<Shift>-J` in the browser and select a `Network` tab in the debug window. Look for error codes like 404 or 500 and resolve problems in your project. Look to the [Django documentation](https://docs.djangoproject.com/en/1.7/howto/static-files/) to read about it in details.

If you use some Django admin style replacements, like django-suit, or django-grapelli, I can not guarantee package compatibility with these packets. You can bounty these issues ([grappelli](https://github.com/nnseva/django-jsoneditor/issues/13) and [suit](https://github.com/nnseva/django-jsoneditor/issues/12)) to force them to be solved.

**Comment by jerickbixly** [comment]
hi @nnseva i checked the jsoneditor app and it was before the staticfiles django app. there were no errors too in the network tab. it is quite likely that there's some other style sheets it was interacting with which made them look like that. 

i'll investigate perhaps at another time in the future. thanks again.
