### ISSUE TITLE
`jsonfield.fields.JSONFormField` doesn't exist anymore

### ISSUE THREAD

**Issue by eshaan7** [nnseva/django-jsoneditor#60]
https://github.com/nnseva/django-jsoneditor/blob/e5e9ee1cae192a82edd303740ca0ef9dad086f72/jsoneditor/fields/django_jsonfield.py#L2

The class `jsonfield.fields.JSONFormField` was removed/changed in the latest version of  `jsonfield` package. ([new `jsonfield.fields` file](https://github.com/rpkilby/jsonfield/blob/master/src/jsonfield/fields.py))

There are 2 solutions that I see:
- either pin the dependency in `setup.py` to `jsonfield==2.0.2`.
- fix for new changes

**Comment by nnseva** [comment]
Hi!

Use `django-jsoneditor/jsoneditor/fields/jsonfield.py` instead of `django-jsoneditor/jsoneditor/fields/django_jsonfield.py` as described in the documentation.

I've just updated the `django-jsoneditor/jsoneditor/fields/jsonfield.py` to be compatible with the last version of `rpkilby/jsonfield` code.
