### ISSUE TITLE
jsonschema readOnly support?

### ISSUE THREAD

**Issue by ifduyue** [nnseva/django-jsoneditor#69]
Hello,

Does django-jsoneditor support jsonschema readOnly? I tried but fields with `"readOnly": True` can still be edited.

**Comment by nnseva** [comment]
In order to restrict editing the JSON value, I would recommend changing the JSONField construction as described [here](https://github.com/nnseva/django-jsoneditor#custom-jsoneditor-initialization). You also could insert any JS dynamic logic there.

Notice anyway, that the hand-written POST request might update the value in such a case, so if you would like to restrict the value editing strongly, it is not enough.

To make the field really forbidden to change, the field should be declared as `editable=False` in the model and included in the `readonly_fields` list of the admin. Although, the JSONEditor widget will not be used in this case, and the field content will be shown as unformatted JSON.

To fix such a problem, you may define an alternative readonly field in the admin, instead of the original, and return the string marked by `mark_safe` with your own HTML formatting code. Notice that this code might use JSONEditor JavaScript classes.

**Comment by ifduyue** [comment]
@nnseva Thanks for the detailed reply, very appreciated.

In my case it's a JSON field containing dynamic arrays and dynamic objects, and some values of these objects can be modified. I've rethinked this scenario, jsonschema readOnly merely indicates a value should not be modified,  extra works must be done to make sure values marked readonly can't be modified, and it's what I did in API. So here I only need to mark these readonly values readonly in the frontend to provide better UX, I think I'll try to achieve it by leveraging JS dynamic logic.
